variables:
  GO_VERSION: "1.18"

stages:
  - build
  - test
  - deploy

.golang_setup:
  image: golang:$GO_VERSION-alpine
  before_script:
    - echo "Start golang build pipeline"
    - go version
  after_script:
    - echo "Finish golang pipeline"

golang:build:
  stage: build
  extends: .golang_setup
  script:
    - chmod +x ./cmd/script/build.sh
    - ./cmd/script/build.sh

golang:test:
  stage: test
  extends: .golang_setup
  script:
    - chmod +x ./cmd/script/test.sh
    - ./cmd/script/test.sh

golang:deploy:
  stage: deploy
  needs: ["golang:build", "golang:test"]
  script:
    - echo "Deploy"