variables:
  GO_VERSION: "1.18"
  API_NAME: "api-bee"

stages:
  - build
  - test
  - deploy

.golang_setup:
  image: golang:$GO_VERSION-alpine
  before_script:
    - echo "Start golang build pipeline"
    - go version
  after_script:
    - echo "Finish golang pipeline"

golang:build:
  stage: build
  needs: []
  extends: .golang_setup
  artifacts:
    paths:
      - "$API_NAME"
    expire_in: 1 week
  script:
    - go build -o $API_NAME -v ./...

golang:test:
  stage: test
  needs: []
  extends: .golang_setup
  script:
    - cd ./tests
    - go test -o api_test


golang:deploy:
  stage: deploy
  needs: ["golang:build", "golang:test"]
  script:
    - echo "Deploy"