variables:
  GO_VERSION: "1.18"
  API_NAME: "api-bee"
  FOLDER: "API"

stages:
  - build
  - test
  - deploy

.golang_setup:
  image: golang:$GO_VERSION-alpine
  needs: []

golang:build:
  stage: build
  extends: .golang_setup
  artifacts:
    expire_in: 30 days
    paths:
      - "./dist"
  script:
    - cd $FOLDER && ./cmd/script/build.sh

golang:test:
  stage: test
  extends: .golang_setup
  script:
    - cd $FOLDER && ./cmd/script/test.sh

golang:deploy:
  stage: deploy
  needs: ["golang:build", "golang:test"]
  script:
    - echo "Deploy"