variables:
  GO_VERSION: "1.18"

stages:
  - build
  - test


.golang_setup:
  image: golang:1.18.2-alpine
  before_script:
    - echo "Start golang build pipeline"
    - go version
  after_script:
    - echo "Finish golang pipeline"

build-code-golang:
  stage: build
  extends: .golang_setup
  script:
    - echo "test"

test-code-test:
  stage: test
  extends: .golang_setup
  script:
    - rake test1