/* tslint:disable */
/* eslint-disable */
/**
 * Bee\'s Dream beekeepers and monodoses APIs
 * Bee\'s Dream beekeepers and monodoses APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: by@carrier.pigeon
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Beekeeper
 */
export interface Beekeeper {
    /**
     * 
     * @type {number}
     * @memberof Beekeeper
     */
    age?: number;
    /**
     * 
     * @type {string}
     * @memberof Beekeeper
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof Beekeeper
     */
    firstname?: string;
    /**
     * 
     * @type {string}
     * @memberof Beekeeper
     */
    lastname?: string;
}

export function BeekeeperFromJSON(json: any): Beekeeper {
    return BeekeeperFromJSONTyped(json, false);
}

export function BeekeeperFromJSONTyped(json: any, ignoreDiscriminator: boolean): Beekeeper {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'age': !exists(json, 'age') ? undefined : json['age'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'firstname': !exists(json, 'firstname') ? undefined : json['firstname'],
        'lastname': !exists(json, 'lastname') ? undefined : json['lastname'],
    };
}

export function BeekeeperToJSON(value?: Beekeeper | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'age': value.age,
        'company': value.company,
        'firstname': value.firstname,
        'lastname': value.lastname,
    };
}

