/* tslint:disable */
/* eslint-disable */
/**
 * Bee\'s Dream beekeepers and monodoses APIs
 * Bee\'s Dream beekeepers and monodoses APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: by@carrier.pigeon
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorsJson
 */
export interface ErrorsJson {
    /**
     * 
     * @type {number}
     * @memberof ErrorsJson
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorsJson
     */
    message?: string;
}

export function ErrorsJsonFromJSON(json: any): ErrorsJson {
    return ErrorsJsonFromJSONTyped(json, false);
}

export function ErrorsJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorsJson {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ErrorsJsonToJSON(value?: ErrorsJson | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
    };
}

