/* tslint:disable */
/* eslint-disable */
/**
 * Bee\'s Dream beekeepers and monodoses APIs
 * Bee\'s Dream beekeepers and monodoses APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: by@carrier.pigeon
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Information
 */
export interface Information {
    /**
     * 
     * @type {string}
     * @memberof Information
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof Information
     */
    firstname?: string;
    /**
     * 
     * @type {string}
     * @memberof Information
     */
    lastname?: string;
}

export function InformationFromJSON(json: any): Information {
    return InformationFromJSONTyped(json, false);
}

export function InformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Information {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'company': !exists(json, 'company') ? undefined : json['company'],
        'firstname': !exists(json, 'firstname') ? undefined : json['firstname'],
        'lastname': !exists(json, 'lastname') ? undefined : json['lastname'],
    };
}

export function InformationToJSON(value?: Information | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company': value.company,
        'firstname': value.firstname,
        'lastname': value.lastname,
    };
}

