/* tslint:disable */
/* eslint-disable */
/**
 * Bee\'s Dream beekeepers and monodoses APIs
 * Bee\'s Dream beekeepers and monodoses APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: by@carrier.pigeon
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Logged
 */
export interface Logged {
    /**
     * 
     * @type {string}
     * @memberof Logged
     */
    token?: string;
    /**
     * 
     * @type {User}
     * @memberof Logged
     */
    user?: User;
}

export function LoggedFromJSON(json: any): Logged {
    return LoggedFromJSONTyped(json, false);
}

export function LoggedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Logged {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function LoggedToJSON(value?: Logged | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'user': UserToJSON(value.user),
    };
}

