/* tslint:disable */
/* eslint-disable */
/**
 * Bee\'s Dream beekeepers and monodoses APIs
 * Bee\'s Dream beekeepers and monodoses APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: by@carrier.pigeon
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelDate
 */
export interface ModelDate {
    /**
     * 
     * @type {string}
     * @memberof ModelDate
     */
    dluo?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelDate
     */
    endofproduction?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelDate
     */
    startofproduction?: string;
}

export function ModelDateFromJSON(json: any): ModelDate {
    return ModelDateFromJSONTyped(json, false);
}

export function ModelDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dluo': !exists(json, 'dluo') ? undefined : json['dluo'],
        'endofproduction': !exists(json, 'endofproduction') ? undefined : json['endofproduction'],
        'startofproduction': !exists(json, 'startofproduction') ? undefined : json['startofproduction'],
    };
}

export function ModelDateToJSON(value?: ModelDate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dluo': value.dluo,
        'endofproduction': value.endofproduction,
        'startofproduction': value.startofproduction,
    };
}

