/* tslint:disable */
/* eslint-disable */
/**
 * Bee\'s Dream beekeepers and monodoses APIs
 * Bee\'s Dream beekeepers and monodoses APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: by@carrier.pigeon
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Beekeeper,
    BeekeeperFromJSON,
    BeekeeperFromJSONTyped,
    BeekeeperToJSON,
} from './Beekeeper';
import {
    ModelDate,
    ModelDateFromJSON,
    ModelDateFromJSONTyped,
    ModelDateToJSON,
} from './ModelDate';

/**
 * 
 * @export
 * @interface Monodose
 */
export interface Monodose {
    /**
     * 
     * @type {Beekeeper}
     * @memberof Monodose
     */
    beekeeper?: Beekeeper;
    /**
     * 
     * @type {ModelDate}
     * @memberof Monodose
     */
    dates?: ModelDate;
    /**
     * 
     * @type {string}
     * @memberof Monodose
     */
    honeyvariety?: string;
    /**
     * 
     * @type {number}
     * @memberof Monodose
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Monodose
     */
    location?: string;
}

export function MonodoseFromJSON(json: any): Monodose {
    return MonodoseFromJSONTyped(json, false);
}

export function MonodoseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Monodose {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'beekeeper': !exists(json, 'beekeeper') ? undefined : BeekeeperFromJSON(json['beekeeper']),
        'dates': !exists(json, 'dates') ? undefined : ModelDateFromJSON(json['dates']),
        'honeyvariety': !exists(json, 'honeyvariety') ? undefined : json['honeyvariety'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'location': !exists(json, 'location') ? undefined : json['location'],
    };
}

export function MonodoseToJSON(value?: Monodose | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'beekeeper': BeekeeperToJSON(value.beekeeper),
        'dates': ModelDateToJSON(value.dates),
        'honeyvariety': value.honeyvariety,
        'id': value.id,
        'location': value.location,
    };
}

