/* tslint:disable */
/* eslint-disable */
/**
 * Bee\'s Dream beekeepers and monodoses APIs
 * Bee\'s Dream beekeepers and monodoses APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: by@carrier.pigeon
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Monodose,
    MonodoseFromJSON,
    MonodoseToJSON,
    Update200Response,
    Update200ResponseFromJSON,
    Update200ResponseToJSON,
} from '../models';

export interface DeleteRequest {
    id: string;
}

export interface AddRequest {
    monodose: Monodose;
}

export interface GetRequest {
    id: string;
}

export interface UpdateRequest {
    monodose: Monodose;
}

/**
 * 
 */
export class MonodoseApi extends runtime.BaseAPI {

    /**
     * If the monodose is not found, a 404 status code will be returned
     * Delete a monodose by Id
     */
    async _deleteRaw(requestParameters: DeleteRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Update200Response>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling _delete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/monodose/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Update200ResponseFromJSON(jsonValue));
    }

    /**
     * If the monodose is not found, a 404 status code will be returned
     * Delete a monodose by Id
     */
    async _delete(requestParameters: DeleteRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Update200Response> {
        const response = await this._deleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * If the request body format is not correct, a 400 status code will be returned
     * Create a new monodose
     */
    async addRaw(requestParameters: AddRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Update200Response>> {
        if (requestParameters.monodose === null || requestParameters.monodose === undefined) {
            throw new runtime.RequiredError('monodose','Required parameter requestParameters.monodose was null or undefined when calling add.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/monodose`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MonodoseToJSON(requestParameters.monodose),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Update200ResponseFromJSON(jsonValue));
    }

    /**
     * If the request body format is not correct, a 400 status code will be returned
     * Create a new monodose
     */
    async add(requestParameters: AddRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Update200Response> {
        const response = await this.addRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * If the monodose is not found, a 404 status code will be returned
     * Return a monodose by Id
     */
    async getRaw(requestParameters: GetRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Monodose>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling get.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/monodose/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MonodoseFromJSON(jsonValue));
    }

    /**
     * If the monodose is not found, a 404 status code will be returned
     * Return a monodose by Id
     */
    async get(requestParameters: GetRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Monodose> {
        const response = await this.getRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * If the are not monodoses, an empty array will be returned
     * Return all monodoses
     */
    async getAllRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<Monodose>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/monodose`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MonodoseFromJSON));
    }

    /**
     * If the are not monodoses, an empty array will be returned
     * Return all monodoses
     */
    async getAll(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<Monodose>> {
        const response = await this.getAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * If the request body format is not correct or the target monodose Id is not found, a 400 status code will be returned
     * Update an existing monodose
     */
    async updateRaw(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Update200Response>> {
        if (requestParameters.monodose === null || requestParameters.monodose === undefined) {
            throw new runtime.RequiredError('monodose','Required parameter requestParameters.monodose was null or undefined when calling update.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/monodose`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MonodoseToJSON(requestParameters.monodose),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Update200ResponseFromJSON(jsonValue));
    }

    /**
     * If the request body format is not correct or the target monodose Id is not found, a 400 status code will be returned
     * Update an existing monodose
     */
    async update(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Update200Response> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
