variables:
  GO_VERSION: "1.18"
  API_NAME: "api-bee"
  FOLDER_API: "API"
  TAG_LATEST: $CI_REGISTRY_IMAGE/golang-api:latest
  CONTAINER_NAME: "c-golang-api"
  WEBHOOK_URL: "https://discord.com/api/webhooks/980753549086564392/yKCWhuKqihxVvVRmVzA7t230BmX-Anyq5DwtTVspVWeMuToQisocofSgOBlhmLfG2-zo"

stages:
  - build
  - test
  - publish
  - notification

.golang_setup:
  image: golang:$GO_VERSION-alpine
  needs: []

golang:build:
  stage: build
  extends: .golang_setup
  artifacts:
    expire_in: 30 days
    paths:
      - "./$FOLDER_API/dist/$API_NAME"
  script:
    - cd $FOLDER_API && go build -o $API_NAME -v ./...

golang:test:
  stage: test
  extends: .golang_setup
  script:
    - cd ./$FOLDER_API/tests && go test -o api_test

golang:publish:
  image: docker:latest
  stage: publish
  needs: ["golang:build", "golang:test"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  tags:
    - deployment
  script:
    - docker login docker-registry.univ-nantes.fr -u $UNIV_LOGIN -p $UNIV_PASSWORD
    - docker build -t $TAG_LATEST ./$FOLDER_API/.
    - docker push $TAG_LATEST

golang:deploy:
  image: alpine:latest
  stage: publish
  needs: ["golang:publish"]
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login docker-registry.univ-nantes.fr -u $UNIV_LOGIN -p $UNIV_PASSWORD"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f $CONTAINER_NAME || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -dp 8080:8080 --name $CONTAINER_NAME $TAG_LATEST"

discord:notification:
  image: alpine:latest
  stage: notification
  tags:
    - deployment
  script:
    - wget https://raw.githubusercontent.com/DiscordHooks/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL
  needs: ["golang:deploy"]
